name: reviewdog
on: [push]
jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: yamllint-github-check
        uses: reviewdog/action-yamllint@c23c5d4cd45b5cc16fa3e6e34073068b228cabeb # v1.17.0
        with:
          github_token: ${{ secrets.github_token }}
          level: error
          fail-on-error: true
          reporter: github-check
          yamllint_flags: "testdata/"