name: reviewdog
on: [push]
jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: yamllint-github-check
        uses: reviewdog/action-yamllint@508148c0d959b166798f9792d1b29dddcac37348 # v1.16.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          yamllint_flags: "testdata/"